name             "bash-completion"
maintainer       "Phil Cohen"
maintainer_email "github@phlippers.net"
license          "MIT"
description      "Installs bash-completion"
version          "0.2.0"

supports "ubuntu"
supports "debian"
supports "centos"
supports "redhat"
supports "fedora"
